bridge-stp.in: automatically start/stop mstpd as needed
This eliminates the need for a separate init script or systemd service
to manage mstpd.

This behavior can be disabled in bridge-stp.conf.

diff --git a/bridge-stp.in b/bridge-stp.in
--- a/bridge-stp.in
+++ b/bridge-stp.in
@@ -23,17 +23,34 @@ bridge=$1
 
 # Define some relevant paths.
 mstpctl='@mstpctlfile@'
-conf_file='@bridgestpconffile@'
-net_dir=/sys/class/net
+mstpd='@mstpdfile@'
+pid_file='@mstpdpidfile@'
+net_dir='/sys/class/net'
 
+# Set default config values.
+# If 'y', mstpd will be automatically started/stopped as needed.
+MANAGE_MSTPD='y'
+# Arguments to pass to mstpd when it is started.
+MSTPD_ARGS=''
 # A space-separated list of bridges for which MSTP should be used in place of
 # the kernel's STP implementation.  If empty, MSTP will be used for all bridges.
 MSTP_BRIDGES=''
 
-# Ensure that mstpctl exists and is executable.
+# Read the config.
+if [ -e '@bridgestpconffile@' ]; then
+    . '@bridgestpconffile@'
+fi
+
+# Ensure that mstpctl and mstpd exist and are executable.
 if [ -z "$mstpctl" ] || [ ! -x "$mstpctl" ]; then
     echo "mstpctl binary does not exist or is not executable" >&2
     exit 2
+fi
+if [ "$MANAGE_MSTPD" = 'y' ]; then
+    if [ -z "$mstpd" ] || [ ! -x "$mstpd" ]; then
+        echo "mstpd binary does not exist or is not executable" >&2
+        exit 2
+    fi
 fi
 
 # Determine whether mstpd should manage STP for the specified bridge.
@@ -54,10 +71,6 @@ is_mstp_bridge()
 
 case $2 in
     start)
-        if [ -e "$conf_file" ]; then
-            . "$conf_file" || exit
-        fi
-
         # Make sure the specified bridge is valid.
         if [ ! -d "$net_dir/$bridge/bridge" ]; then
             echo "'$bridge' is not a bridge" >&2
@@ -70,10 +83,27 @@ case $2 in
             exit 10
         fi
 
-        # Make sure mstpd is running.
+        # Start mstpd if necessary.
         if ! pidof -c -s mstpd >/dev/null; then
-            echo 'mstpd is not running' >&2
-            exit 3
+            if [ "$MANAGE_MSTPD" != 'y' ]; then
+                echo 'mstpd is not running' >&2
+                exit 3
+            fi
+            echo 'mstpd is not running'
+            echo 'Starting mstpd ...'
+            "$mstpd" $MSTPD_ARGS || exit 3
+
+            # Due to kernel locks, mstpd will not respond to mstpctl until after
+            # this script exits, so `mstpctl addbridge` must be run as an
+            # asynchronous background process.
+            # If `mstpctl addbridge` fails, we could turn STP off and back on
+            # again to fall back to kernel STP mode.  However, that could cause
+            # an infinite loop if mstpd is being started successfully but is
+            # then dying before or when mstpctl connects to it.  To avoid that
+            # possibility, we instead simply turn STP off if `mstpctl addbridge`
+            # fails.
+            ( "$mstpctl" addbridge "$bridge" || brctl stp "$bridge" off ) &
+            exit 0
         fi
 
         # Add bridge to mstpd.
@@ -82,6 +112,32 @@ case $2 in
     stop)
         # Remove bridge from mstpd.
         "$mstpctl" delbridge "$bridge" || exit 3
+
+        # Exit if mstpd should not be stopped when it is no longer used.
+        if [ "$MANAGE_MSTPD" != 'y' ]; then
+            exit 0
+        fi
+
+        # Exit if any other bridges are using mstpd.
+        for bridge in $(ls "$net_dir"); do
+            # Ignore interfaces that are not bridges.
+            if [ ! -e "$net_dir/$bridge/bridge/stp_state" ]; then
+                continue
+            fi
+
+            # Ignore bridges that should not use MSTP.
+            if ! is_mstp_bridge "$bridge"; then
+                continue
+            fi
+
+            # If bridge is in user_stp mode, then it is probably using MSTP.
+            if [ "$State" = '2' ]; then
+                exit 0
+            fi
+        done
+
+        # Kill mstpd, since no bridges are currently using it.
+        kill $(pidof -c mstpd)
         ;;
     *)
         echo "Unknown action: $2" >&2
